kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: media
  namespace: default
spec:
  selector:
    matchLabels:
      name: default-media
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Pi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: app-data
  namespace: default
spec:
  selector:
    matchLabels:
      name: app-data
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Pi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: monitoring-data
  namespace: default
spec:
  selector:
    matchLabels:
      name: monitoring-data
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Pi
