repositories:
  - name: authelia
    url: https://charts.authelia.com/ 

environments:
  default:
    values:
      - "../values.yaml.gotmpl"
---

releases:
  - name: authelia
    chart: authelia/authelia
    atomic: true
    values:
      - domain: {{ .Values.rootDomain }}
        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: nginx
            external-dns.alpha.kubernetes.io/target: {{ .Values.tls.cert.dnsNames.authelia }}
            cert-manager.io/cluster-issuer: letsencrypt-cluster-issuer
          subdomain: {{ .Values.services.authelia.subdomain }}
          tls:
            secret: authelia-cert-tls
        pod:
          kind: Deployment
        configMap:
          authentication_backend:
            disable_reset_password: true
            ldap:
              enabled: false
            file:
              enabled: true
          session:
            expiration: 1d
            inactivity: 10m
            redis:
              enabled: false
          storage:
            postgres:
              host: {{ .Values.network.postgres.host }}
          totp:
            issuer: Authelia
          access_control:
            default_policy: one_factor
          notifier:
            smtp:
              enabled: false
              {{- /*
                    #  username: {{ .Values.services.authelia.smtpUsername }}
                    #  password: {{ .Values.services.authelia.smtpUsername }}
                    #  sender: {{ .Values.services.authelia.smtpUsername }}
                    #  host: {{ .Values.services.authelia.smtpUsername }}
                */}}
            filesystem:
              enabled: true
        secret:
          storage:
            value: {{ .Values.services.authelia.dbPass }}
             
        persistence:
          enabled: true
          subPath: "authelia"
          existingClaim: app-data
