{{- if and .Values.networkPolicies.enabled .Values.mail.relay.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "matrix.fullname" . }}-exim-relay
  labels:
{{ include "matrix.labels" . | indent 4 }}
{{ include "matrix.mail.labels" . | indent 4}}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "matrix.fullname" . }}-exim-relay
      app.kubernetes.io/instance: {{ .Release.Name }}
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: {{ include "matrix.name" . }}-synapse
          app.kubernetes.io/instance: {{ .Release.Name }}
    ports:
      - port: smtp
        protocol: TCP
{{- end }}
