kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ .Release.Name }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Release.Name }}
  ingress:
  - ports:
    - port: 3000
    from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: ingress-nginx
