apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jellyfin
  annotations:
    kubernetes.io/ingress.class: "nginx"
    external-dns.alpha.kubernetes.io/target: {{ .Values.dnsName }}
spec:
  tls:
    - hosts:
        - {{ .Values.dnsName }}
      secretName: jellyfin-cert-tls
  rules:
    - host: {{ .Values.dnsName }}
      http:
        paths:
          - path: /
            backend:
              serviceName: jellyfin
              servicePort: jellyfin-http
