---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: jellyfin
  name: jellyfin
spec:
  ports:
  - name: jellyfin-http
    port: 8096
    protocol: TCP
    targetPort: 8096
  selector:
    app: jellyfin
    #  type: ClusterIP
