apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    external-dns.alpha.kubernetes.io/target: {{ .Values.dnsName }}
spec:
  tls:
    - hosts:
      - {{ .Values.dnsName }}
      secretName: habit-accountability-cert-tls
  rules:
    - host: {{ .Values.dnsName }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}
                port:
                  name: habits-http
    - host: habitaccountability.kube.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}
                port:
                  name: habits-http
