kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: organizer
spec:
  podSelector:
    matchLabels:
      app: organizer
  ingress:
  - ports:
    - port: 80
    - port: 443
    from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: ingress-nginx
