apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: librespeed
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issue: letsencrypt-cluster-issuer
spec:
  tls:
    - hosts:
        - {{ .Values.dnsName }}
      secretName: librespeed-cert-tls
  rules:
    - host: {{ .Values.dnsName }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: librespeed
                port:
                  name: libspeed-http

