apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: heimdall
  annotations:
    kubernetes.io/ingress.class: "nginx"
    #nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    #nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    external-dns.alpha.kubernetes.io/target: "heimdall.kube.local"
spec:
    #  tls:
    #    - hosts:
    #        - heimdall.kube.local
  rules:
    - host: heimdall.kube.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: heimdall
                #servicePort: heimdall-https
                port:
                  name: heimdall-http
