apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: freshrss
  annotations:
    kubernetes.io/ingress.class: "nginx"
    external-dns.alpha.kubernetes.io/target: {{ .Values.dnsName }}
spec:
  tls:
    - hosts:
        - {{ .Values.dnsName }}
      secretName: freshrss-cert-tls
  rules:
    - host: {{ .Values.dnsName }}
      http:
        paths:
          - path: /
            backend:
              serviceName: freshrss
              servicePort: freshrss-http
