repositories:
  - name: k8s-at-home
    url: https://k8s-at-home.com/charts/ 

environments:
  default:
    values:
      - "../values.yaml.gotmpl"
---

releases:
  - name: searx
    namespace: default
    chart: k8s-at-home/searx
    atomic: true
    values:
      - controllerType: deployment
        strategy:
          type: Recreate
        image:
          repository: searx/searx
          tag: 1.0.0
          pullPolicy: IfNotPresent
        service:
          annotations:
            prometheus.io/probe: "true"
            prometheus.io/protocol: http
        searx:
          baseUrl: "https://{{ .Values.tls.cert.dnsNames.searx }}"
          mortyKey: {{ .Values.services.searx.mortyKey }}
        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: "nginx"
            external-dns.alpha.kubernetes.io/target: {{ .Values.tls.cert.dnsNames.searx }}
            cert-manager.io/cluster-issuer: letsencrypt-cluster-issuer
            nginx.ingress.kubernetes.io/auth-url: "https://{{ .Values.tls.cert.dnsNames.authelia }}/api/verify"
            nginx.ingress.kubernetes.io/auth-signin: "https://{{ .Values.tls.cert.dnsNames.authelia }}/"
          hosts:
            - host: {{ .Values.tls.cert.dnsNames.searx }}
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - hosts:
                - "{{ .Values.tls.cert.dnsNames.searx }}"
              secretName: searx-cert-tls
