{{- if and .Values.networkPolicies.enabled .Values.bridges.irc.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "matrix.fullname" . }}-bridge-irc
  labels:
  {{ include "matrix.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "matrix.fullname" . }}-bridge-irc
      app.kubernetes.io/instance: {{ .Release.Name }}
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: {{ include "matrix.name" . }}-synapse
              app.kubernetes.io/instance: {{ .Release.Name }}
      ports:
        - port: bridge
          protocol: TCP
{{- end }}
