apiVersion: v1
name: Daily Dictionary Digest
version: 1.0.0
appVersion: v1.0.0
description: python email application to send me a daily email digest of birthdays occurring today or occurring this month if the exact date is not known
