apiVersion: v1
kind: Service
metadata:
  name: {{ include "jitsi-meet.name-prosody" . }}
  labels:
{{ include "jitsi-meet.labels" . | indent 4 }}
spec:
  type: {{ .Values.prosody.service.type }}
  ports:
    - port: 5222
      targetPort: c2s1
      protocol: TCP
      name: c2s1
    - port: 5269
      targetPort: c2s2
      protocol: TCP
      name: c2s2
    - port: 5280
      targetPort: web
      protocol: TCP
      name: web
    - port: 5347
      targetPort: xmpp
      protocol: TCP
      name: xmpp
  sessionAffinity: ClientIP
  selector:
    app.kubernetes.io/name: {{ include "jitsi-meet.name-prosody" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
