{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "jitsi-meet.serviceAccountName" . }}
  labels:
{{ include "jitsi-meet.labels" . | indent 4 }}
{{- end -}}
