apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kanboard
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: letsencrypt-cluster-issuer
spec:
  tls:
    - hosts:
        - {{ .Values.dnsName }}
      secretName: kanboard-cert-tls
  rules:
    - host: {{ .Values.dnsName }}
      http:
        paths:
          - path: /
            backend:
              serviceName: kanboard
              #servicePort: heimdall-https
              servicePort: kanboard-http
